apiVersion: v1
kind: Secret
metadata:
  name: catwatch-secrets
type: Opaque
stringData:
  tg-token: "YOUR_TELEGRAM_BOT_TOKEN"
  bot-api-key: "YOUR_STATIC_BOT_API_KEY"
  google-client-id: "YOUR_GOOGLE_CLIENT_ID"
  google-client-secret: "YOUR_GOOGLE_CLIENT_SECRET"
  google-redirect-url: "https://yourdomain.com/auth/google/callback"
  auth-success-redirect: "https://yourdomain.com/"
  db-password: "YOUR_POSTGRES_PASSWORD"
